[build]
  # Diretório de publicação
  publish = "."
  
  # Comando de build (não necessário para HTML estático)
  command = "echo 'Build concluído'"

[build.environment]
  # Versão do Node.js (caso necessário no futuro)
  NODE_VERSION = "18"

[[headers]]
  # Aplicar headers para todos os arquivos
  for = "/*"
  [headers.values]
    # Cache control
    Cache-Control = "public, max-age=31536000"
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache mais curto para HTML
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Configurações de redirecionamento
[[redirects]]
  from = "/"
  to = "/apresentacao.html"
  status = 200